<?php

define('CHECK_METADATA', true);

define('CHECK_FILE', true);

define('IN_METADATA', 'plugins.generic.duplicateDetector.where.metadata');

define('IN_FILE', 'plugins.generic.duplicateDetector.where.file');

//define('SUBMISSION', true);

define('EXCERPT_LENGTH', 4000);

define('DUPLICATE_DETECTION_FILE_RATIO_THRESHOLD', 80);

define('DUPLICATE_DETECTION_METADATA_RATIO_THRESHOLD', 80);

define('DUPLICATE_METADATA_LENGTH_THRESHOLD', 50);

?>
